Repository swieomswieomlab/black_bean, pull requests merged in 2023-06, with the labels that each got.

#32 Name make
  lib/main.dart
  lib/pages/name_make.dart
Labels: enhancement, 예찬, function

#31 Wrong exam
  lib/main.dart
  lib/pages/full_exam.dart
  lib/pages/wrong_exam_page.dart
Labels: 영찬, UI

#33 [UI] Select Unit Exam
  lib/pages/select_unit_exam_page.dart
Labels: 예찬, UI

#34 [UI] Full Exam UI fixed
  lib/pages/full_exam.dart
  lib/pages/select_full_exam_page.dart
Labels: 예찬, UI

#36 Landing page
  assets/images/shiumshium.png
  lib/main.dart
  lib/pages/home_page.dart
  lib/pages/landing_page.dart
  lib/pages/select_unit_exam_page.dart
  pubspec.yaml
Labels: 영찬, UI

#39 [UI] modify UI
  lib/pages/full_exam.dart
  lib/pages/grading_page.dart
  lib/pages/landing_page.dart
  lib/pages/problem_make.dart
  lib/pages/select_full_exam_page.dart
  lib/pages/select_unit_exam_page.dart
  lib/pages/unit_exam.dart
  lib/pages/unit_exam_grading_page.dart
  lib/textstyle.dart
Labels: 영찬, UI

#41 Wrong exam function
  lib/class/grading_arguments.dart
  lib/main.dart
  lib/model/full_grading_arguments.dart
  lib/model/wrong_exam_arguments.dart
  lib/pages/full_exam.dart
  lib/pages/full_exam_grading_page.dart
  lib/pages/grading_page.dart
  lib/pages/home_page.dart
  lib/pages/image_change.dart
  lib/pages/name_make.dart
  lib/pages/problem_make.dart
  lib/pages/select_full_exam_page.dart
  lib/pages/test_page.dart
  lib/pages/unit_exam.dart
  lib/pages/wrong_exam_page.dart
  lib/service/firebase_service.dart
Labels: bug, enhancement, 예찬, function, UI

#42 [FUNC] SmallSection functions
  lib/pages/wrong_exam_page.dart
  lib/service/firebase_service.dart
Labels: 예찬, function

#43 [UI] Button Style Change
  lib/pages/full_exam_grading_page.dart
Labels: 예찬, UI
