Repository swieomswieomlab/black_bean, pull requests merged in 2023-05, with the labels that each got.

#10 Full exam page submit function
  lib/pages/full_exam.dart
  lib/pages/grading_page.dart
Labels: 예찬, function

#12 Select exam page g UI
  lib/pages/select_exam_page.dart
Labels: 영찬, UI

#11 [FUNC] Load MajorSubject Names
  lib/model/major_section_name.dart
  lib/pages/test_page.dart
  lib/service/firebase_service.dart
Labels: 예찬, function

#13 [UI] select_exam_page dialog 추가
  lib/pages/select_exam_page.dart
Labels: 영찬, UI

#14 Unit exam page selecting area color
  lib/main.dart
  lib/pages/unit_exam.dart
Labels: 영찬, UI

#15 Db functions
  lib/components.dart
  lib/main.dart
  lib/model/problem.dart
  lib/pages/full_exam.dart
  lib/pages/grading_page.dart
  lib/pages/home_page.dart
  lib/pages/image_picker_test.dart
  lib/pages/problem_make.dart
  lib/pages/select_exam_page.dart
  lib/pages/test_page.dart
  lib/pages/weakness_exam.dart
  lib/service/firebase_service.dart
  pubspec.lock
  pubspec.yaml
  test/function_test.dart
Labels: 예찬, function

#17 Utility funcions
  lib/model/problem.dart
  lib/pages/full_exam.dart
Labels: enhancement, 예찬

#18 Full exam grading page UI
  lib/main.dart
  lib/pages/full_exam.dart
  lib/pages/full_exam_grading_page.dart
Labels: 예찬, UI

#19 [DEBUG] SingleChildScrollView error 해결
  lib/pages/unit_exam.dart
Labels: bug, UI

#20 [UI] full_exam grading Resize
  lib/pages/full_exam_grading_page.dart
Labels: 예찬, UI

#22 [FUNC] UnitExamGradingPageFunctionsAndRouting
  lib/main.dart
  lib/pages/full_exam.dart
  lib/pages/unit_exam.dart
  lib/pages/unit_exam_grading_page.dart
Labels: 예찬, function, UI

#21 Route to full exam grading page
  lib/main.dart
  lib/pages/full_exam.dart
  lib/pages/full_exam_grading_page.dart
Labels: 예찬, function

#23 UI modify
  assets/fonts/Pretendard-Medium.otf
  lib/components.dart
  lib/main.dart
  lib/pages/select_exam_page.dart
  lib/pages/select_full_exam_page.dart
  lib/pages/unit_exam.dart
  lib/textstyle.dart
  pubspec.yaml
Labels: 영찬, UI

#28 Routing flow
  lib/main.dart
  lib/model/unit_exam_arguments.dart
  lib/pages/select_unit_exam_page.dart
  lib/pages/unit_exam.dart
  lib/pages/unit_exam_grading_page.dart
  lib/service/firebase_service.dart
Labels: 예찬, function, UI

#27 Problem make page substitute
  .firebase/hosting.YnVpbGQvd2Vi.cache
  lib/main.dart
  lib/pages/problem_make.dart
Labels: 예찬, function

#29 [UI,FUNC] Routing flow full
  lib/main.dart
  lib/pages/full_exam.dart
  lib/pages/full_exam_grading_page.dart
  lib/pages/unit_exam.dart
Labels: 예찬, function, UI

#30 [UI,FUNC] Full_exam 라우팅 및 ui 정리
  lib/main.dart
  lib/model/full_exam_arguments.dart
  lib/pages/full_exam.dart
  lib/pages/select_full_exam_page.dart
  lib/pages/test_page.dart
Labels: 예찬, function, UI
